### ISSUE TITLE
No such file or directory: 'glove/glove.6B.50d.txt'

### ISSUE THREAD

**Issue by ymz1124** [wabyking/qnn#5]
你好，请问是否可以上传一下glove/glove.6B.50d.txt，否则无法复现论文结果

**Comment by wabyking** [comment]
You could find it from http://nlp.stanford.edu/data/glove.6B.zip . Thanks

**Comment by ymz1124** [comment]
> You could find it from http://nlp.stanford.edu/data/glove.6B.zip . Thanks

Thanks！
